version: "3"

services:
  pihole:
    build: .
    container_name: pihole
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "80:80/tcp"
      - "443:443/tcp"
      # - "67:67/udp"  # Uncomment to enable DHCP server
    environment:
      TZ: Europe/Zurich
      WEBPASSWORD: changeme
    volumes:
      - ./etc-pihole:/etc/pihole
      - ./etc-dnsmasq.d:/etc/dnsmasq.d
    restart: unless-stopped
